server:
  port: 9000
spring:
  application:
    name: galio-gateway
  profiles:
    active: @profiles.active@

---
# nacos 配置
spring:
  cloud:
    nacos:
      discovery:
        group: ${nacos.discovery.group}
        namespace: ${nacos.discovery.namespace}
        server-addr: ${nacos.server-addr}
      config:
        group: ${nacos.config.group}
        namespace: ${nacos.config.namespace}
        server-addr: ${nacos.server-addr}

---
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      service-config:
        galio-auth:
          group-name: 鉴权服务
          order: 1
        galio-system-biz:
          group-name: 系统服务
          order: 1
      version: openapi3