spring:
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
  cloud:
    inetutils:
      # 择符合前缀的IP作为服务注册IP
      preferred-networks: 221.218.136
nacos:
  server-addr: 123.249.127.25:8848
  discovery:
    group: DEFAULT_GROUP
    namespace: dev
  config:
    group: DEFAULT_GROUP
    namespace: dev