server:
  port: 9210

spring:
  application:
    name: galio-auth
  profiles:
    active: @profiles.active@

---
spring:
  cloud:
    nacos:
      server-addr: ${nacos.server-addr}
      discovery:
        group: ${nacos.discovery.group}
        namespace: ${nacos.discovery.namespace}
      config:
        group: ${nacos.config.group}
        namespace: ${nacos.config.namespace}
        server-addr: ${nacos.server-addr}