spring:
  config:
    # 此配置 暂且放在application-{profile}文件中，避免放到主配置文件时config.import引入的文件优先于application-{profile}加载
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
  cloud:
    inetutils:
      # 择符合前缀的IP作为服务注册IP
      preferred-networks: 221.218.136
nacos:
  server-addr: 123.249.127.25:8848
  discovery:
    group: DEFAULT_GROUP
    namespace: dev
  config:
    group: DEFAULT_GROUP
    namespace: dev