spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${datasource.system-postgres.url}
    username: ${datasource.system-postgres.username}
    password: ${datasource.system-postgres.password}